{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "granite-3-3-8b.fullname" . }}-metrics
  labels:
    {{- include "granite-3-3-8b.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for direct pod access
  ports:
  - name: metrics
    port: {{ .Values.monitoring.serviceMonitor.metricsPort }}
    targetPort: 8080
    protocol: TCP
  selector:
    serving.kserve.io/inferenceservice: {{ include "granite-3-3-8b.fullname" . }}
{{- end }}
