{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "llama3-2-3b.fullname" . }}
  labels:
    {{- include "llama3-2-3b.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - port: metrics
    path: {{ .Values.monitoring.serviceMonitor.metricsPath }}
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "llama3-2-3b.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: metrics
  namespaceSelector:
    {{- toYaml .Values.monitoring.serviceMonitor.namespaceSelector | nindent 4 }}
{{- end }}
